### ISSUE TITLE
Bugs in SamplerRank1 gaussian_basisReduction function?

### ISSUE THREAD

**Issue by mmp** [utk-team/utk#16]
I get the following warnings about uninitialized variables when I compile:
```
In file included from /Users/mmp/src/utk/src/samplers/Rank1_2dd.cpp:1:
/Users/mmp/src/utk/src/samplers/SamplerRank1.hpp:111:30: warning: variable 'gamma' is uninitialized when used here [-Wuninitialized]
                long long b11 = (nb / d) * gamma;
                                           ^~~~~
/Users/mmp/src/utk/src/samplers/SamplerRank1.hpp:107:24: note: initialize the variable 'gamma' to silence this warning
                int a1, a2, b3, gamma;
                                     ^
                                      = 0
/Users/mmp/src/utk/src/samplers/SamplerRank1.hpp:117:21: warning: variable 'b3' is uninitialized when used here [-Wuninitialized]
                b2.y = b11 * gy + b3 * nb;
                                  ^~
/Users/mmp/src/utk/src/samplers/SamplerRank1.hpp:107:17: note: initialize the variable 'b3' to silence this warning
                int a1, a2, b3, gamma;
                              ^
                               = 0
2 warnings generated.
```
Looking at the code, they seem to be legitimate.

**Comment by dcoeurjo** [comment]
Indeed, that's weird.. I'm my test, I usually use the Fibonacci mode for Rank1 (which does not use this methods) but the general approach is strange.

This code comes from additional material of https://link.springer.com/article/10.1007/s11390-015-1535-0, let me double check the correct setting for the Gaussian reduction step.

**Comment by dcoeurjo** [comment]
It looks like the variables are init using the commented extended Euclidean computation.. This should fix the warning: https://github.com/utk-team/utk/commit/4d9c541f6d405106feef3920d1ba259fc89a2fe6
