### ISSUE TITLE
Black Fourier PNG and all-NaN values in power spectrum

### ISSUE THREAD

**Issue by mmp** [utk-team/utk#17]
Attached is a zip file with "random.dat", which has 128 realizations of 1024 uniform random 2D samples.

If I run `~/build/utk/src/spectral/Fourier_2dd -i random.dat -P x.png --Pdat x.dat`, the resulting PNG is entirely black and the first few lines of the power spectrum file are:
```
-4      -4      nan
-3.96875        -4      nan
-3.9375 -4      nan
-3.90625        -4      nan
-3.875  -4      nan
-3.84375        -4      nan
-3.8125 -4      nan
```

(Am I doing something wrong?)

[random.zip](https://github.com/utk-team/utk/files/5632066/random.zip)

**Comment by mmp** [comment]
(I should add, I get reasonable results if I use e.g. the `penrose4096.dat` file linked from https://utk-team.github.io/utk/spectral_fourier/, so presumably my installation isn't totally broken.)

**Comment by dcoeurjo** [comment]
thanks @mmp for the feedback, I'll have a look into it..
