### ISSUE TITLE
Pair Correlation Function

### ISSUE THREAD

**Issue by xchhuang** [utk-team/utk#22]
Hi,

I have a question regarding the implementation of PCF in utk [here](https://github.com/utk-team/utk/blob/master/src/statistics/PCF.hpp). Following [the reference paper](https://cgl.ethz.ch/Downloads/Publications/Papers/2012/Ozt12b/Ozt12b.pdf), I don't see where the `factor` term (line 96-98) comes from. Would it be possible to add comments for this? Thanks in advance.

**Comment by dcoeurjo** [comment]
Hi,
If I remember correctly, the factors correspond to the V_d / \partial V_d ratio (volume of a unit ball divided by the area of that ball).

**Comment by xchhuang** [comment]
Hi @dcoeurjo ,

This makes sense. thank you!
