### ISSUE TITLE
Javascript/HTML website issue

### ISSUE THREAD

**Issue by dcoeurjo** [utk-team/utk#33]
The "Exe", "C++", "Python" panes are not working properly (the code snippet is shifted)

(Safari)

<img width="729" alt="Capture d’écran 2023-09-24 à 20 18 14" src="https://github.com/utk-team/utk/assets/700165/2e2b2928-b8e5-478a-8d06-4eb94c8a0f6a">

**Comment by BDoignies** [comment]
This was a problem with screen size. I removed the 'float' properties in the CSS so that the block is ALWAYS below. Don't know why it was there in the first place...

Fixed in :  28b633600f6ca6d1625cdda196bce8992bec2c72
