### ISSUE TITLE
Cleaning up issues and old branches

### ISSUE THREAD

**Issue by BDoignies** [utk-team/utk#38]
Hello,

Looking at the branches in the repository, it seems that some of them point to the old UTKversion, while others are merged PRs. What about removing them from the git ? 

- Merged PR of UTK 2.0: 
    - doc-scrambling
    - Paulin212223
    - GaussianIntegrationTest
    - SobolIndicesJoe
    - SobolInitTable

- UTK 1.0 branches:
    - BuildEdits
    - dcoeurjo-patch-1 
    - lloyd
    - pcf 
    - refactoring

There is also this issue is still open and looked fixed according to last comment:  "Bugs in SamplerRank1 gaussian_basisReduction function? #16"

**Comment by dcoeurjo** [comment]
Let me check the old branches ;)

**Comment by dcoeurjo** [comment]
done
