### ISSUE TITLE
Missing images (point sets, spectrum..) for the new samplers

### ISSUE THREAD

**Issue by dcoeurjo** [utk-team/utk#39]
Missing images in the doc for SOT, Cascaded, and may all the recent samplers

**Comment by BDoignies** [comment]
See branch "Update-Doc" : https://github.com/utk-team/utk/tree/Update-Doc.

I also added missing figures for Bridson and BNOT, and an example for GenrativeMatrices (G. Larcher and F. Pillichshammer net).

As far as I can tell, all samplers (except for 1D VdC and 3D Lloyd) now have point sets and spectrum.
