### ISSUE TITLE
Licence?

### ISSUE THREAD

**Issue by ddiakopoulos** [utk-team/utk#5]
Hi! Great work on this project. I couldn't find an explicit `LICENSE` file in the root of the repo, nor any uniform license text block in the headers of most files. 

It seems some of the the (minor?) dependencies are GPL.

**Comment by dcoeurjo** [comment]
Hi @ddiakopoulos,

We’ll clarify this. Thanks for reporting it. 
Basically, the most of the project will be LGPL-like. 

The tools requiring CGAL (for instance) would be GPL only.

**Comment by ddiakopoulos** [comment]
Thanks for the speedy response!

**Comment by dcoeurjo** [comment]
WIP in PR #11

**Comment by dcoeurjo** [comment]
Fixed in the merged PR. Thanks @ddiakopoulos for the issue (and sorry for the delay ;))
