### ISSUE TITLE
Compilation error with cgal 4.11

### ISSUE THREAD

**Issue by Plopounet13** [utk-team/utk#7]
Hi,
while trying to compile utk with cgal 4.11 I get this error for the file TriangleArrangement.hpp and BoxesAligned.hpp

/utk/src/integration/../integration/arrangements/TriangleArrangement.hpp: In member function ‘void utk::TriangleArrangement::rasterizerPS(unsigned int, const char*, bool)’:
/utk/src/integration/../integration/arrangements/TriangleArrangement.hpp:330:41: error: ‘const FT {aka const class __gmp_expr<__mpq_struct [1], __mpq_struct [1]>}’ has no member named ‘to_double’
   pt[0] = origin->target()->point().x().to_double()*normalisation_factor;

Here is a full copy of the error output:
[error.txt](https://github.com/utk-team/utk/files/2572385/error.txt)

**Comment by dcoeurjo** [comment]
Fixed in https://github.com/utk-team/utk/commit/9d4801e5240eb803b5f49e3a199ed62b03331388

thx
